import { Outfit } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} flex h-screen w-screen`}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
